### ISSUE TITLE
Incorrect links in README

### ISSUE THREAD

**Issue by hackyourlife** [NoneGiven/MphRead#1]
It looks like the README.md has a few incorrect links:

- `mph-viewer by hackyourlife` points to https://github.com/McKay42/mph-model-viewer although it should probably point to https://github.com/hackyourlife/mph-viewer
- `hackyourlife's model viewer` points to https://github.com/hackyourlife/mph-viewer/issues although it should probably point to https://github.com/hackyourlife/mph-viewer (= the main project page, not the issues page)

**Comment by NoneGiven** [comment]
Fixed, thanks for that.
