### ISSUE TITLE
Low jumper force

### ISSUE THREAD

**Issue by ch-mcl** [NoneGiven/MphRead#104]
Any jumper force(distance, height) is lower in Outer Reach.

1st floor(ammo and 3 jumpers putted floor): 
jumper push up hunters to 3rd floor. 
But it height is bit lower than NDS. (Hunters can’t reach 3rd floor without jump action.)

3rd floor (missile ammo putted floor):
Jumper lunch hunters other side.
But it’s distance is shorter than NDS.(Hunters can’t reach other side.)

**Comment by NoneGiven** [comment]
Fixed in 0.23.2.0. Thanks for the bug reports.
