### ISSUE TITLE
Sound sfx loops wrong point

### ISSUE THREAD

**Issue by ch-mcl** [NoneGiven/MphRead#105]
Charge sfx sounds play When you charge weapons.
But it’s sfx sounds loop wrong point.
Charge sfx sounds has 2sections.
"Start” and “Ready”.
“Start” section is only plays starting charge. 

NDS:
“Start”, "Ready”, "Ready”, “Ready", …(loops "Ready" section).

mphread:
“Start”, "Ready”, “**Start**", "Ready”, …(loops “Start”and"Ready" section).

**Comment by NoneGiven** [comment]
Fixed in 0.24.0.0 (finally).
