### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by LukeGreatwow** [NoneGiven/MphRead#106]
Sorry, I didn't know where else i could ask this. Is this project going to recieve any more updates to make it function as a complete game or has it fulfilled it's intended purpose already?

**Comment by zachHixson** [comment]
Curious about this too. I'd love to help contribute in some way

**Comment by Kicool-Grumm** [comment]
Asking the same here! Definitely would love music support and it fully supporting the game's sequences.

**Comment by NoneGiven** [comment]
It's not dead, I've just been busy and unmotivated. These are roughly the features I still want to implement:

* Bosses
* Story, saves, menus
* Bot AI
* Music

As for contributing, there are certain rough edges like the audio system, which is a mess and doesn't work properly when using OpenAL-Soft, and the input system, which has some kind of mouse coordinate/speed/DPI bug, that I will eventually get around to fixing, but I would welcome contributions to. There's also music playback, which I haven't touched yet.

It would be harder for anyone to contribute to actual game implementation unless you want to get involved with the reverse engineering side of things.

Hopefully I'll get back to working on the project soon. If anyone wants to chat about it, you can find me in `#mph-hacking` in [this Discord server](https://discord.gg/AX3V9DG5) (invite is good for 7 days).
