### ISSUE TITLE
Toggle vertex colors and toggle wireframe not working

### ISSUE THREAD

**Issue by SCSR-is-too-short-username** [NoneGiven/MphRead#107]
As the title says, pressing the toggle vertex colors or toggle wireframe buttons don't do anything (except for if you are controlling Samus, you morph/unmorph when trying to toggle vertex colors)

**Comment by NoneGiven** [comment]
You have to use `Ctrl+C` and `Ctrl+Q` for these features, to avoid conflicts with players controls. I just forgot to update the controls display and the wiki.
