### ISSUE TITLE
[Feature request] Collison view mode

### ISSUE THREAD

**Issue by SCSR-is-too-short-username** [NoneGiven/MphRead#108]
(I'm assuming that this doesn't exist yet, as I didn't find one)

Can you add a mode that allows the user to view room (and optionally solid object, like elevators) collision data. I know the visuals and collision don't always line up. One example from rooms where you can get out of bounds, the floor is usually a rectangle even if the in bounds floor isn't, leaving collision behind corners and inside some inner walls, etc. It would be nice to take a look at different areas (especially places you can go out of bounds) and see if there is something interesting, like overlapping collision, gaps in collision, etc.

It would be good to be able to also hide visuals to be able to see collision in areas where (and if) visuals and collision don't overlap (like when collision is behind the texture).

Additionally viewing collision normals would be also nice and color them differently (like red) if the normal doesn't point the expected direction (I'm assuming this can be calculated when the points that make the plane are known).

**Comment by NoneGiven** [comment]
https://github.com/NoneGiven/MphRead/wiki/Visualization-Guide#Collision
