### ISSUE TITLE
Can't export hunters in Blender 4.0

### ISSUE THREAD

**Issue by makidoll** [NoneGiven/MphRead#110]
Using the version `0.22.1.0` and ROM `USA Rev 1 (AMHE1)`, I'm trying to `MphRead.exe -export Samus_lod0` and I'm getting strange results. I tried imported the dae file in Blender 4.0 and 2.79b and even the script file.

The wiki uses `Trace_lod0` as an example here: https://github.com/NoneGiven/MphRead/wiki/Setup-&-Export-Guide#Exporter
And this too yielded similar results.

Samus does render fine in the model viewer though.

![Screenshot from 2024-01-19 15-54-01](https://github.com/NoneGiven/MphRead/assets/8362329/271457cb-7373-42b1-9a4e-f5821f16a5d5)

**Comment by makidoll** [comment]
I read this from her: https://github.com/McKay42/mph-model-viewer

This project also exports the same

> Character models don't really work, since all bones are centered at (0,0,0), and their textures are broken

**Comment by NoneGiven** [comment]
Hunter model import won't work without using the script, and right now, it looks like Blender 4.0 introduced some new scripting errors. You can use Blender 3.x or wait until I push a fix for 4.0.

**Comment by makidoll** [comment]
I used the script to import the hunters and it yielded the same results. I had fixed the script for Blender 4.0 and tried older versions

**Comment by NoneGiven** [comment]
0.23.0.0 has been released with a fix for this issue. Re-export your models using the new version of MphRead, and make sure the `mph_common.py` file in your Blender scripts path is replaced with the new version too (and Blender is relaunched after that).

Also, I added minimum version support for import/export, so in the future, models won't have to be re-exported whenever mph_common.py is updated.

**Comment by makidoll** [comment]
Ooh! Awesome! I was able to try it out and got a model I can work with. Thank you so much! I really appreciate it.

Apart from the script needing a couple tweaks to get fully working, I had an issue on Linux where it was resolving paths using backslashes instead of forward slashes. I had to run the program in wine.

**Comment by NoneGiven** [comment]
Was the path issue in the import script, or with MphRead itself? Should be fixable if you can let me when/where it happened.

**Comment by makidoll** [comment]
It's the tool itself. I modified the project a couple weeks ago to fix the issue. I could create a pull request if you'd like.

**Comment by makidoll** [comment]
The error reads something like this:

`Unhandled exception. System.IO.FileNotFoundException: Could not find file '/home/maki/git/MphRead/src/MphRead/bin/Debug/net6.0/files/AMHE1/_archives\Samus\Samus_lod0_Model.bin'.`

Looking through `Metadata.cs`, there are hundreds of paths with backslashes. Using `Path.Combine` uses the right directory separator. I think it might be best to make a function that validates paths before passing them to `File.*` functions. The backwards slash can just be converted to forward slash on Linux and it'll be fine.

**Comment by NoneGiven** [comment]
TBH, I thought `Path.Combine()` would normalize/adjust the paths correctly for the OS. Turns out that's not true; the only thing it does is use the correct OS separator when joining the strings you give it.

I'll push a fix.

**Comment by NoneGiven** [comment]
Closing with the release of 0.23.1.0 to fix the path separators. Please let me know if there are any further issues on Linux with this release.
