### ISSUE TITLE
"Modules" folder should be lowercase

### ISSUE THREAD

**Issue by thelabcat** [NoneGiven/MphRead#128]
Blender expects the modules folder in script directories to be all lowercase [as seen in the docs](https://docs.blender.org/manual/en/latest/editors/preferences/file_paths.html#modules), but here it is capitalized. On Windows, this doesn't matter because file paths are case-insensitive, but on UNIX they are case-sensitive. So, unless the "Modules" folder is renamed to "modules", UNIX imports do not work.

**Comment by NoneGiven** [comment]
You can copy `mph_common.py` to your modules folder instead of using the folder within MphRead. But I'll update this in the next release.
