### ISSUE TITLE
Rooms are not found by description, only name

### ISSUE THREAD

**Issue by thelabcat** [NoneGiven/MphRead#130]
I ran `./MphRead -export "Docking Bay"` and got `No model or room with the name Docking Bay could be found.` However, `./MphRead -export UNIT2_RM8` worked.
I was using Fedora 40 x64.

**Comment by NoneGiven** [comment]
This is the expected behavior. We can't export by in-game names because they're not unique.

**Comment by thelabcat** [comment]
But [the official setup and export guide](https://github.com/NoneGiven/MphRead/wiki/Setup-&-Export-Guide#exporter) says:

Models can be exported with the -export argument. There is no recolor index, and either a model name or room name may be passed. Examples:

```
MphRead -export Trace_lod0
MphRead -export Gorea1A_lod0
MphRead -export UNIT3_RM4
**MphRead -export "Gorea Prison"**
```

**Comment by thelabcat** [comment]
If that information is incorrect, it should be changed.

**Comment by NoneGiven** [comment]
"Gorea Prison" is the room name, not the description/in-game name. See https://github.com/NoneGiven/MphRead/wiki/Rooms.

> To view or export a room, use the value of the Name column.

**Comment by thelabcat** [comment]
Ooh, I see. I might suggest using a different example, though, since that is one of the few room names that looks like a description. Still, the information is correct. Sorry.
